### ISSUE TITLE
Sorting algorithms for arrays with elements containing a custom versioning

### ISSUE THREAD

**Issue by dcasota** [dfinke/SortingAlgorithms#2]
Hi there,

Recently I wanted to figure out the latest version in an array containing custom versioning.

The array contained all `tzdata*.tar.gz` names from `https://data.iana.org/time-zones/releases`.

A simple `$array | sort-object | select-object -last 1` does not find `2023c` as latest.

Not using the built-in powershell function, means to sort the array manually.

The following code - 99% based on your heapsort algorithmus -  is a modification hack. 

In MaxHeapify, `$targetList[$left]`, `$targetList[$index]` and `$targetList[$largest]` are compared as binary (= int64) by concatenating each converted ascii to a '000' decimal format. E.g. `2023c` result in `05004805005199`.

It works but only for a length-restricted custom versioning.

```
class HeapSort {
# Heapsort algorithmus from Doug Finke
# https://github.com/dfinke/SortingAlgorithms/blob/master/HeapSort.ps1
# modified to compare concated ascii code values
    [array] static Sort($targetList) {
        $heapSize = $targetList.Count

        for ([int]$p = ($heapSize - 1) / 2; $p -ge 0; $p--) {
            [HeapSort]::MaxHeapify($targetList, $heapSize, $p)
        }

        for ($i = $targetList.Count - 1; $i -gt 0; $i--) {
            $temp = $targetList[$i]
            $targetList[$i] = $targetList[0]
            $targetList[0] = $temp

            $heapSize--
            [HeapSort]::MaxHeapify($targetList, $heapSize, 0)
        }
        return $targetlist
    }

    static MaxHeapify($targetList, $heapSize, $index) {
        $left = ($index + 1) * 2 - 1
        $right = ($index + 1) * 2
        $largest = 0

        if ($left -lt $heapSize -and [int64]([system.string]::concat((([system.Text.Encoding]::Default.GetBytes($targetList[$left])) | % tostring 000))) -gt [int64]([system.string]::concat((([system.Text.Encoding]::Default.GetBytes($targetList[$index])) | % tostring 000)))) {
            $largest = $left
        }
        else {
            $largest = $index
        }

        if ($right -lt $heapSize -and [int64]([system.string]::concat((([system.Text.Encoding]::Default.GetBytes($targetList[$right])) | % tostring 000))) -gt [int64]([system.string]::concat((([system.Text.Encoding]::Default.GetBytes($targetList[$largest])) | % tostring 000)))) {
            $largest = $right
        }

        if ($largest -ne $index) {
            $temp = $targetList[$index]
            $targetList[$index] = $targetList[$largest]
            $targetList[$largest] = $temp

            [HeapSort]::MaxHeapify($targetList, $heapSize, $largest)
        }
    }
}
```

It is a hack because it is length-restricted and it might not fit for other custom versionings as well.

To give a 2nd example, `https://invisible-island.net/archives/dialog` contains a custom versioning e.g. `1.3-20180621`.

I'm not a Powershell expert. The idea of heapsort as base allows to add a kind of regex expression for the custom versioning and to eliminate the hack restrictions.

I hope the description of the initial situation and the solution is understandable.

**Comment by dfinke** [comment]
Really interesting. Good stuff. I will let it percolate in my head.

Thanks!

**Comment by dcasota** [comment]
very rare use case -> close
